---
title: "COVID-19 in Saudi Arabia"
description: |
  A short description of the post.
author:
  - name: Xiaoyu Tian
date: 09-01-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggplot2)
library(DT)
library(sf)
library(rnaturalearth)
library(ggthemes)
library(kableExtra)

```

```{r}
load(here::here("data/coronavirus.rda"))
```


```{r}
#list of middle east countries
mideastname <- c("Bahrain",
 "Cyprus",
 "Egypt",
 "Iran",
 "Iraq",
 "Israel",
 "Jordan",
 "Kuwait",
 "Lebanon",
 "Oman",
 "Qatar",
 "Saudi Arabia",
 "Syria",
 "Turkey",
 "United Arab Emirates",
 "Yemen")
```




```{r}
mideast <- ne_countries(country = mideastname, returnclass = "sf", scale = "medium") %>% 
  select(name, pop_est)

cases <- coronavirus %>% group_by(country, lat, long, type) %>% 
  summarise(cases = sum(cases)) %>% 
  ungroup()

mideast_cases <- cases %>% right_join(mideast, by = c("country" = "name"))

```


```{r}
mideast_confirmed <- mideast_cases %>% 
  filter(type %in% "confirmed") %>% 
  mutate('Cases in thousands'= as.integer(cases/1000) )

mideast_confirmed %>% 
  ggplot()+
  geom_sf(mapping = aes(geometry = geometry, fill = `Cases in thousands`), size = 0.3) +
  theme_map()+
  scale_fill_gradient2(low = "grey", mid = "white", high = "brown", midpoint = .02)+
  theme(legend.position = "right", panel.background = element_rect(fill = 'aliceblue')) +
  geom_sf_text(mapping = aes(geometry = geometry, label = country), data = mideast_confirmed, stat = "sf_coordinates", nudge_x = 0,
  nudge_y = 0,
  check_overlap = FALSE)+
  labs(title = " Total number of cases (in thousands) confirmed in Middle East areas")
```

```{r}
table_mideast <- coronavirus %>% 
  right_join(mideast, by = c("country" = "name")) %>% 
  group_by(country, pop_est) %>%
  summarise(cases = sum(cases)) %>% 
  mutate(`Infection Rate %` = round(100*cases/pop_est, 2)) %>% 
  arrange(desc(cases)) %>% 
  rename("Country" = country,  "Population"= pop_est, "Total Number of Infection" = cases) 

table_mideast$`Rank of Least Infection Rate` <- c("7","6","5","10", "9", "11","12","4","13","8","3","16","15","14","2","1")

```
```{r}
datatable(table_mideast,
          options = list(),
          class = "display",
          caption = "Table 1: This table displays the Covid-19 infection rates in the middle east countries")
```
























